apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nfs-data-grafana
  namespace: monitoring
  labels:
    app: grafana
spec:
  storageClassName: nfs-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
