apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nfs-mysql
  namespace: mysql
  labels:
    app: mysql
spec:
  storageClassName: nfs-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
