apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc1
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: k8s-sigs.io/nfs-provisioner
  resources:
    requests:
      storage: 5Gi
